# -*- coding: utf-8 -*-
"""Draftly carousel content - 15 premium verticals with production-grade prompts."""

from __future__ import annotations

from typing import Any


def _img(p1: str, p2: str, p3: str) -> str:
    return f"{p1}\n\n{p2}\n\n{p3}"


def _site(p1: str, p2: str, p3: str) -> str:
    return f"{p1}\n\n{p2}\n\n{p3}"


CAROUSELS: list[dict[str, Any]] = [
    {
        "slug": "01_Premium_Earphones",
        "title": "Premium Earphones",
        "product_label": "Apple AirPods Pro",
        "cover_hook": "Stop shipping static product pages. Prompt a scroll-synced launch site that moves like the hardware itself.",
        "website_prompt": _site(
            "Build a premium wireless earphone launch page for a flagship noise-cancelling product in the Apple AirPods Pro category. The site should feel calm, precise, and hardware-first: floating centered nav pill with links Features, Sound, Specs, Pre-order; hero headline 'Hear Everything. Feel Nothing Else.' with subcopy about adaptive ANC, personalized spatial audio, and a 30-hour MagSafe charging case.",
            "Scroll sections after the hero: three feature cards (Adaptive Noise Cancellation, Transparency Mode, Personalized Spatial Audio), a comparison strip versus generic earbuds, a spec table with IP54 rating, Bluetooth 5.3, and USB-C case charging, plus customer quote slider with star ratings. Include a sticky pre-order CTA with color swatches (white, black, midnight blue) and delivery estimate chip.",
            "Typography: minimal grotesque sans, generous whitespace, product-first layout. Palette: soft white hero transitioning into deep charcoal footer. Motion behavior: hero background scrubs with scroll using extracted video frames. No cluttered marketplace grid - this is a flagship launch, not a catalog listing.",
        ),
        "image_prompt": _img(
            "Cinematic photoreal hero still for a scroll-scrubbed earphone landing page. No text, no logos, no UI chrome, 16:9 landscape suitable for 200+ extracted frames. Scene opens on two premium white wireless earbuds with short stems on brushed aluminum - one earbud lifted slightly above a half-open charging case with a soft green status LED.",
            "Material detail: glossy white plastic with subtle micro-scratches, mesh grilles sharp at macro level, hinge shadow under case lid, caustic reflections on metal surface. Environment: deep charcoal gradient background fading to near-black at edges, faint atmospheric haze, negative space on left third for future headline overlay.",
            "Lighting and camera: soft key from upper left, cool rim from right for edge definition, shallow depth of field with creamy bokeh, filmic contrast, premium consumer electronics campaign quality. Color direction: clean whites, cool gray shadows, one subtle cyan reflection - never neon, never oversaturated AI blue.",
        ),
        "first_frame_prompt": "Opening keyframe - wide product tableau. Earbuds sealed inside closed case on reflective dark stone surface, lid shut, LED off, lots of negative space, cool studio top light, same visual world as hero still, 16:9, no text.",
        "last_frame_prompt": "Closing keyframe - both earbuds floating above open case at dynamic three-quarter angle, LED glowing soft green, camera 15% closer than opening frame, stronger rim light on stem edges, same charcoal environment, no text, photoreal.",
        "video_prompt": "Slow cinematic dolly-in from wide closed-case composition toward floating open-case hero. Gentle parallax on reflection, subtle rotation of right earbud revealing mesh grille, premium product reveal pacing, seamless 6-second loop, no text overlays, no strobe.",
        "why_website": "Earphone buyers decide in seconds. A scroll-synced cinematic page proves build quality before they read specs. Static Shopify themes flatten premium hardware into generic grids. Draftly lets you brief the full experience - hero motion, feature rhythm, and pre-order urgency - in one prompt pipeline.",
        "result_headline": "Hear Everything. Feel Nothing Else.",
        "result_notes": "Shipped scroll site with floating nav, spatial audio section, spec table, and pre-order strip layered over generated hero frames.",
    },
    {
        "slug": "02_Luxury_Clothing",
        "title": "Luxury Clothing",
        "product_label": "Maison Aurel Capsule",
        "cover_hook": "Fashion brands sell feeling first. Your website should scroll like a lookbook, not load like a catalog.",
        "website_prompt": _site(
            "Create a luxury minimalist fashion house landing page for Maison Aurel autumn capsule. Navigation: wordmark left, links Collection, Atelier, Journal, Contact in muted uppercase tracking. Hero headline 'Tailored Silence' with subhead about Italian wool, hand-finished seams, and a limited 200-piece run.",
            "Scroll sections: three editorial lookbook panels in asymmetric grid, fabric macro strip with touch copy, size guide accordion, boutique locator for Paris, London, Milan, and waitlist email capture with serif accent on Aurel. Include craftsmanship timeline (spinning, cutting, finishing) and press quote band.",
            "Palette: warm ivory, charcoal, single burgundy accent on primary CTA. Feel like Celine meets Acne Studios - restrained, expensive, slow scroll rhythm. Background scrubs through editorial frames as user scrolls. No discount banners or countdown gimmicks.",
        ),
        "image_prompt": _img(
            "High-fashion editorial environment for scroll-scrubbed website frames. No text, no logos, 16:9 cinematic aspect. Scene: model silhouette in oversized camel wool coat walking through foggy concrete arcade, morning side light cutting through columns, fabric texture visible at collar.",
            "Motion suggestion in still: coat hem with subtle motion blur implying forward walk, heavy negative space left third for headline overlay, desaturated warm stone grays and camel tones, fine film grain, Vogue campaign quality.",
            "Camera: 50mm equivalent, eye-level, soft atmospheric perspective deepening toward background arches. Avoid HDR crunch, avoid plastic AI skin, avoid oversaturated blues. This is quiet luxury, not fast fashion energy.",
        ),
        "first_frame_prompt": "Wide architectural corridor, model small in frame wearing camel coat, heavy negative space left, fog softening columns, golden side light, editorial fashion still, no text.",
        "last_frame_prompt": "Medium crop on coat fabric texture at shoulder and collar, model turned three-quarter, warmer light, tighter composition, same arcade environment, no text.",
        "video_prompt": "Slow lateral tracking shot following model walk through arcade at natural walking pace. Fabric moves realistically, fog drifts subtly, editorial fashion film pacing, seamless loop, no text.",
        "why_website": "Luxury DTC needs editorial pacing online. One hero photo is not enough. Scroll-synced motion mimics runway rhythm and justifies premium price before checkout.",
        "result_headline": "Tailored Silence",
        "result_notes": "Editorial scroll site with lookbook grid, fabric macro, waitlist capture, and boutique locator over cinematic frames.",
    },
    {
        "slug": "03_Performance_Sneakers",
        "title": "Performance Sneakers",
        "product_label": "Velocity Pro Runner",
        "cover_hook": "Runners buy energy and proof. Your site should feel fast before the first click.",
        "website_prompt": _site(
            "Build a performance running shoe launch page for Velocity Pro - elite marathon trainer with carbon plate and nitrogen-infused foam. Nav: VELOCITY logo, links Technology, Athletes, Reviews, Shop. Hero headline 'Every Gram Earned' with kinetic subcopy about energy return and sub-7oz weight.",
            "Sections: exploded-view tech diagram with callouts, marathon athlete testimonial carousel, pace calculator widget mockup, colorway picker (volt, black, glacier), retailer map, and buy-now strip with live size availability. Include split comparison vs previous model.",
            "Dark hero transitioning to light tech section. Typography bold grotesque. Motion: track surface scrubs beneath product on scroll. Nike-adjacent energy without copying trademarks.",
        ),
        "image_prompt": _img(
            "Dynamic performance running shoe environment for scroll frames. No text, 16:9. Single volt-yellow and black running shoe suspended mid-stride above wet asphalt track at blue hour, water droplets frozen in air, carbon plate faintly visible through translucent midsole.",
            "Stadium lights creating long shadows, motion energy in composition, hyper-real sport photography, shallow depth with track lines leading to horizon. Surface texture: wet rubber granules reflecting light.",
            "Color grade: cool blue ambient with warm volt accent on shoe. Camera low angle, 35mm, slight upward tilt. No lens flare spam, no CGI plastic shine.",
        ),
        "first_frame_prompt": "Shoe planted on starting block, wide track environment, pre-sprint tension, low angle, blue hour lighting, no text.",
        "last_frame_prompt": "Same shoe airborne mid-stride, droplets trailing, tighter crop on midsole tech, identical track lighting, no text.",
        "video_prompt": "Explosive slow-motion push-in as shoe lifts off block. Subtle track blur, dynamic sports reveal, high energy 5-second loop, no text overlays.",
        "why_website": "Performance footwear sells tech stories - foam, plate, weight. A cinematic scroll site turns specs into sensation and lifts conversion on high-AOV SKUs.",
        "result_headline": "Every Gram Earned",
        "result_notes": "Dark-to-light scroll site with tech diagram, athlete quotes, colorway picker, and shop strip.",
    },
    {
        "slug": "04_Specialty_Coffee",
        "title": "Specialty Coffee",
        "product_label": "Origin and Ember Roasters",
        "cover_hook": "Third-wave coffee is ritual. Prompt a site that feels warm before the first paragraph.",
        "website_prompt": _site(
            "Design a specialty coffee roaster landing page for Origin and Ember - single-origin micro-lot subscription brand. Nav: Roastery, Origins, Subscribe, Wholesale. Hero 'Roasted For The Quiet Hour' with subcopy on Ethiopian Yirgacheffe and Guatemalan Huehuetenango lots.",
            "Sections: interactive origin map with clickable regions, roast date transparency block, subscription tiers (Explorer, Devotee, Ritual), brew guide accordion, wholesale inquiry form, bean bag grid with tasting notes (blueberry, cocoa, citrus).",
            "Warm parchment and espresso brown palette. Scroll-synced roastery atmosphere in hero. Typography mix of grotesque headlines and readable body. No generic cafe template stock photos.",
        ),
        "image_prompt": _img(
            "Artisan coffee roastery hero environment for scroll-scrubbed frames. No text, 16:9. Steam rising from pour-over dripper on wooden bar, morning sun through warehouse window, burlap sacks soft in background, copper kettle glint.",
            "Shallow DOF on blooming coffee grounds in dripper, warm amber tones, cozy third-wave aesthetic. Human-scale props: ceramic cup edge, linen napkin fold, subtle chalk menu board blur.",
            "Lighting: natural window key with warm fill, gentle steam wisps catching light. Camera straight-on slightly above bar height. Avoid oversaturated orange Instagram filter look.",
        ),
        "first_frame_prompt": "Wide roastery interior, drum roaster silhouette, soft steam haze, golden morning light through windows, no text.",
        "last_frame_prompt": "Close pour-over bloom with steam ribbon rising, warm highlights on liquid surface, intimate crop, no text.",
        "video_prompt": "Gentle dolly toward pour-over setup. Steam wisps drift upward, liquid shimmer in dripper, calm morning ritual pacing, seamless loop.",
        "why_website": "Coffee brands compete on story and freshness. A scroll-driven site layers origin, roast date, and ritual without rebuilding every seasonal lot in code.",
        "result_headline": "Roasted For The Quiet Hour",
        "result_notes": "Warm scroll site with origin map, subscription tiers, brew guides, and micro-lot product grid.",
    },
    {
        "slug": "05_Artisan_Cafe",
        "title": "Artisan Cafe",
        "product_label": "Hearth and Bloom Bakery",
        "cover_hook": "Neighborhood cafes win on atmosphere. Your homepage should feel like pushing the door open.",
        "website_prompt": _site(
            "Create a boutique cafe and bakery landing page for Hearth and Bloom. Nav: Menu, Bakery, Events, Visit. Hero 'Where The Oven Meets The Morning' with hours and address chip.",
            "Sections: today pastry lineup cards, coffee menu with prices, sourdough origin timeline, private event inquiry form, gallery strip, embedded map with Join us this weekend CTA. Include dietary icons and seasonal special banner.",
            "Palette: cream, terracotta, sage green accents. Scroll hero uses warm interior frames. Friendly grotesque typography, not corporate SaaS.",
        ),
        "image_prompt": _img(
            "Inviting artisan cafe interior for scroll frames. No text, 16:9. Fresh croissants and latte art on marble counter, soft window light, dried flowers in vase, handwritten menu board blurred background.",
            "Warm hygge atmosphere, shallow depth, lifestyle photography. Steam from espresso machine edge frame, flour dust on wooden board subtle detail.",
            "Morning color temperature 5200K leaning warm. Camera at customer eye line across counter. Avoid cluttered junk, avoid neon signs.",
        ),
        "first_frame_prompt": "Wide cafe interior, empty chairs, oven glow from kitchen pass, morning calm, no text.",
        "last_frame_prompt": "Counter close-up with pastry stack and latte, warmer tones, human-scale intimacy, no text.",
        "video_prompt": "Slow pan across counter from wide to pastry close-up. Natural window light shift, cozy documentary feel, seamless loop.",
        "why_website": "Cafes live on local discovery and vibe. A prompt-built cinematic page keeps your seasonal menu current without agency retainers.",
        "result_headline": "Where The Oven Meets The Morning",
        "result_notes": "Hospitality scroll site with menu cards, bakery story, events form, and visit map.",
    },
    {
        "slug": "06_Boutique_Hotel",
        "title": "Boutique Hotel",
        "product_label": "The Vale House",
        "cover_hook": "Guests book the promise of arrival. Prompt a site that feels like checking in before they pack.",
        "website_prompt": _site(
            "Build a boutique hotel landing page for The Vale House - 18-room countryside retreat with spa and farm-to-table restaurant. Nav: Rooms, Dining, Spa, Experiences, Book. Hero 'Arrive Slowly. Leave Restored.' with availability search mockup.",
            "Sections: room cards (Garden Suite, Loft, Pavilion) with amenity icons, spa treatment menu, chef story, seasonal experience calendar, testimonial slider, direct booking CTA bypassing OTAs.",
            "Palette: linen white, forest green, brushed brass accents. Scroll hero uses arrival driveway frames. Elegant serif accent on quotes only.",
        ),
        "image_prompt": _img(
            "Luxury boutique hotel arrival scene for scroll frames. No text, 16:9. Stone manor entrance at dusk, warm interior glow through tall windows, gravel drive, subtle mist in hedgerows.",
            "Inviting hospitality cinematography, rich muted colors, symmetrical composition with door as focal point. Lantern light pools on path stones.",
            "Camera at driveway height, 40mm, gentle depth falloff. No oversaturated sunset, no HDR halos.",
        ),
        "first_frame_prompt": "Distant wide shot of manor at golden hour, long drive leading inward, no text.",
        "last_frame_prompt": "Closer entrance with lit doorway and lobby warmth visible, dusk deepening, no text.",
        "video_prompt": "Slow forward glide along drive toward lit entrance. Welcoming hospitality reveal, subtle mist movement, seamless loop.",
        "why_website": "Hotels lose margin to OTAs. A cinematic direct-booking site sells the stay emotionally before aggregator fees.",
        "result_headline": "Arrive Slowly. Leave Restored.",
        "result_notes": "Hospitality scroll site with room cards, spa menu, dining story, and direct book CTA.",
    },
    {
        "slug": "07_Luxury_Bed_Linen",
        "title": "Luxury Bed Linen",
        "product_label": "Somerset and Co Linen",
        "cover_hook": "Sleep brands sell texture and trust. Flat product grids kill the tactile story.",
        "website_prompt": _site(
            "Design a luxury bed linen DTC page for Somerset and Co - European flax linen, 160 GSM, OEKO-TEX certified. Nav: Sheets, Bundles, Care, About. Hero 'Sleep In Soft Architecture' with stonewashed Belgian flax subcopy.",
            "Sections: fabric feel explainer with macro swatches, bundle builder, thread-count myth panel, care guide, sustainability sourcing map, 100-night trial banner.",
            "Palette: oatmeal, soft gray, white spa aesthetic. Scroll hero uses bedroom frame sequence. Minimal copy, maximum texture.",
        ),
        "image_prompt": _img(
            "Serene bedroom linen scene for scroll frames. No text, 16:9. Unmade bed with rumpled oatmeal linen sheets, morning light across folds showing weave texture, neutral Scandinavian bedroom.",
            "Soft shadows, calm luxury lifestyle. Visible flax weave at fold edges, wooden bedside table edge, sheer curtain glow.",
            "Camera slightly elevated three-quarter view. Color palette restrained warm neutrals. Avoid hotel stock photo sterility.",
        ),
        "first_frame_prompt": "Wide bedroom, bed small in frame, sheer curtains glowing, peaceful morning, no text.",
        "last_frame_prompt": "Macro linen fold texture filling frame, visible weave, warm side light, no text.",
        "video_prompt": "Slow drift from wide bedroom to linen texture macro. Gentle fabric shadow movement, ASMR-calm pacing, seamless loop.",
        "why_website": "Linen buyers need to feel fabric online. Macro motion and scroll rhythm simulate touch better than flat grids.",
        "result_headline": "Sleep In Soft Architecture",
        "result_notes": "Spa-minimal scroll site with fabric macro, bundle builder, care guide, and trial banner.",
    },
    {
        "slug": "08_Premium_Watch",
        "title": "Premium Watch",
        "product_label": "Meridian Automatic",
        "cover_hook": "Horology is detail at distance. Prompt macro intimacy with brand restraint.",
        "website_prompt": _site(
            "Create a premium automatic watch launch page for Meridian Automatic - 40mm steel diver, in-house calibre, 200m water resistance. Nav: Collection, Movement, Craft, Reserve. Hero 'Time, Engineered Quietly' with dial macro.",
            "Sections: exploded movement diagram, case finishing gallery, heritage timeline since 1987, retail partner map, waitlist for blue dial variant, spec sheet with sapphire crystal and 48h reserve.",
            "Dark luxury palette with silver highlights. Scroll hero uses dial-to-case frame progression.",
        ),
        "image_prompt": _img(
            "Luxury watch product scene for scroll frames. No text, 16:9. Stainless steel diver on dark wet stone, dial catching soft spotlight, bezel detail sharp, water droplets on case.",
            "Moody horology advertising, high contrast controlled. Reflection on sapphire crystal, brushed vs polished case surfaces visible.",
            "Camera macro-capable, top-down angle 30 degrees. No fake luxury cliches like wine glasses unless subtle blur.",
        ),
        "first_frame_prompt": "Watch flat on stone, wide composition, moody top light, full case visible, no text.",
        "last_frame_prompt": "Extreme dial macro, hands at 10:10, sapphire reflection, tight crop, no text.",
        "video_prompt": "Slow orbit around watch case. Light travels across brushed steel, dial catches highlight, precision luxury pacing, seamless loop.",
        "why_website": "Watch buyers research for weeks. Scroll-synced macro sections beat static hero plus PDF spec dumps.",
        "result_headline": "Time, Engineered Quietly",
        "result_notes": "Dark luxury scroll site with movement diagram, finishing gallery, heritage timeline, and waitlist.",
    },
    {
        "slug": "09_Clean_Skincare",
        "title": "Clean Skincare",
        "product_label": "Lumen Botanica",
        "cover_hook": "Skincare buyers want clarity and calm - not ingredient walls on a generic template.",
        "website_prompt": _site(
            "Build a clean skincare brand page for Lumen Botanica - dermatologist-tested botanical serums, fragrance-free, vegan. Nav: Shop, Ingredients, Routine, Science. Hero 'Your Skin, Less Noise' with product trio.",
            "Sections: ingredient glossary in plain English, 3-step routine builder, transparency policy, clinical stats (87% brightness in 4 weeks), subscription save 20%, derm quote callout.",
            "Soft sage, white, glass aesthetic. Scroll hero uses botanical shadow play on product stills.",
        ),
        "image_prompt": _img(
            "Clean beauty product still life for scroll frames. No text, 16:9. Three minimal glass serum bottles on wet white surface with eucalyptus leaf shadows, soft diffused studio light.",
            "Clinical yet organic, premium skincare photography. Condensation micro-droplets on glass, subtle reflection underneath bottles.",
            "Camera straight-on, even soft box lighting, high key but not blown highlights. Avoid plastic CGI skin products look.",
        ),
        "first_frame_prompt": "Wide trio arrangement, lots of white space, soft shadow play, no text.",
        "last_frame_prompt": "Single hero serum center, condensation droplets, leaf shadow accent, no text.",
        "video_prompt": "Slow push-in on center serum bottle. Leaf shadow drifts subtly, clean clinical calm, seamless loop.",
        "why_website": "Skincare needs education plus trust fast. Scroll narrative reduces bounce and support tickets.",
        "result_headline": "Your Skin, Less Noise",
        "result_notes": "Clinical-clean scroll site with ingredient glossary, routine builder, study stats, and subscription CTA.",
    },
    {
        "slug": "10_Designer_Sunglasses",
        "title": "Designer Sunglasses",
        "product_label": "Optic Atelier",
        "cover_hook": "Eyewear is identity on your face - prompt a site as sharp as the frames.",
        "website_prompt": _site(
            "Design a designer sunglasses landing page for Optic Atelier - handmade acetate, polarized CR-39 lenses, limited drops. Nav: Frames, Lookbook, Craft, Shop. Hero 'See The World Sharper' with coastal blur background.",
            "Sections: frame shape guide, lens polarization explainer, acetate craft video slot, virtual try-on placeholder, drop countdown, free shipping bar.",
            "High-contrast fashion palette: black, sand, gold. Scroll hero uses lens reflection sequence.",
        ),
        "image_prompt": _img(
            "Designer sunglasses fashion scene for scroll frames. No text, 16:9. Tortoise acetate aviators on marble with coastal sunlight streak, lens showing subtle sky reflection.",
            "Fashion accessory photography, crisp shadows, elegant negative space. Acetate pattern detail visible at temple.",
            "Hard sunlight with controlled shadow geometry. Camera slightly above table height. No cheap mall kiosk vibe.",
        ),
        "first_frame_prompt": "Glasses on marble wide frame, harsh elegant sunlight, shadow geometry, no text.",
        "last_frame_prompt": "Three-quarter angle glasses, lens sky reflection, tighter fashion crop, no text.",
        "video_prompt": "Slow arc around frames on marble. Sunlight shifts across acetate pattern, controlled lens flare, fashion reveal loop.",
        "why_website": "Eyewear DTC fights returns. Lookbook motion and shape education upfront cut hesitation.",
        "result_headline": "See The World Sharper",
        "result_notes": "Fashion-forward scroll site with shape guide, lens science, craft story, and drop countdown.",
    },
    {
        "slug": "11_Luxury_Handbags",
        "title": "Luxury Handbags",
        "product_label": "Maison Valetta Tote",
        "cover_hook": "A five-figure bag needs a site that feels hand-finished - not a theme store.",
        "website_prompt": _site(
            "Build a luxury handbag launch page for Maison Valetta structured top-handle tote. Nav: Collection, Craft, Atelier, Waitlist. Hero 'Carry Quiet Power' with subcopy on full-grain calfskin, saddle stitching, and numbered edition of 500.",
            "Sections: atelier process gallery (cut, edge paint, stitch), interior organization diagram, personalization monogram preview, care guide, waitlist with deposit option.",
            "Ivory, espresso brown, gold hardware accents. Scroll hero uses leather texture macro progression.",
        ),
        "image_prompt": _img(
            "Luxury handbag hero still for scroll frames. No text, 16:9. Structured cognac leather tote on travertine plinth, gold hardware catching soft window light, silk scarf accent muted.",
            "Macro leather grain visible, edge paint flawless, handle drop shadow on stone. Background warm gallery wall blur.",
            "Editorial fashion product lighting, 85mm compression, shallow DOF. Avoid fake logo emboss, avoid plastic leather sheen.",
        ),
        "first_frame_prompt": "Wide shot tote centered on plinth, gallery context, soft side light, no text.",
        "last_frame_prompt": "Macro handle and stitching detail, tighter crop, warmer highlight, no text.",
        "video_prompt": "Slow arc around bag on plinth. Light slides across leather grain and hardware, quiet luxury pacing, seamless loop.",
        "why_website": "Handbag buyers purchase craft proof. Scroll macro sections sell stitching and leather before price.",
        "result_headline": "Carry Quiet Power",
        "result_notes": "Atelier scroll site with craft gallery, interior diagram, monogram preview, and waitlist.",
    },
    {
        "slug": "12_Artisan_Perfume",
        "title": "Artisan Perfume",
        "product_label": "Nocturne Atelier No. 07",
        "cover_hook": "Fragrance is invisible luxury. Your site should feel like opening the bottle.",
        "website_prompt": _site(
            "Create a niche perfumery landing page for Nocturne Atelier No. 07 - unisex amber woody extrait. Nav: Scents, Notes, Story, Shop. Hero 'Memory In A Bottle' with note pyramid (bergamot, iris, sandalwood, amber).",
            "Sections: perfumer letter, wearing guide by season, sample trio offer, boutique stockists map, limited batch counter.",
            "Dark amber glass aesthetic with cream typography. Scroll hero uses vapor and glass refraction frames.",
        ),
        "image_prompt": _img(
            "Artisan perfume hero for scroll frames. No text, 16:9. Square amber extrait bottle on black stone with single beam of light, faint vapor mist, label blank/minimal.",
            "Glass refraction caustics on stone, gold cap detail, moody perfumery campaign lighting. Negative space for headline.",
            "Macro-capable camera, low key lighting, warm amber tones. Avoid cheap mall fragrance cliches.",
        ),
        "first_frame_prompt": "Wide bottle on stone with vapor haze, dramatic single light, no text.",
        "last_frame_prompt": "Close cap and neck with refraction caustics, tighter crop, no text.",
        "video_prompt": "Slow push-in toward bottle as vapor drifts through light beam. Glass shimmer, intimate luxury pacing, seamless loop.",
        "why_website": "Perfume sells story and notes. Scroll narrative replaces flat product tile grids.",
        "result_headline": "Memory In A Bottle",
        "result_notes": "Dark luxe scroll site with note pyramid, perfumer letter, sample offer, and stockist map.",
    },
    {
        "slug": "13_Designer_Furniture",
        "title": "Designer Furniture",
        "product_label": "Arcform Lounge Chair",
        "cover_hook": "Furniture is spatial. Prompt a site that lets people feel the room before they measure.",
        "website_prompt": _site(
            "Design a designer furniture product page for Arcform Lounge Chair - mid-century walnut frame, boucle upholstery. Nav: Piece, Materials, Room, Configure. Hero 'Sit In Sculpted Comfort' with dimensions overlay.",
            "Sections: 360 material swatches, craftsmanship joinery gallery, room placement suggestions, lead time and white-glove delivery, trade program link.",
            "Warm walnut, cream boucle, soft gray backdrop. Scroll hero moves through living room frame sequence.",
        ),
        "image_prompt": _img(
            "Designer furniture hero for scroll frames. No text, 16:9. Arcform lounge chair in sunlit minimal living room, walnut frame grain visible, boucle texture at arm curve.",
            "Floor shadow soft, large window light, adjacent side table blur, architectural interior photography.",
            "Camera corner angle showing chair profile and room depth. Natural color, no orange filter.",
        ),
        "first_frame_prompt": "Wide room with chair small in frame, window light, architectural context, no text.",
        "last_frame_prompt": "Medium chair profile with upholstery texture sharp, tighter crop, no text.",
        "video_prompt": "Slow dolly past chair revealing profile and material detail. Natural light shift, interior film pacing, seamless loop.",
        "why_website": "Furniture buyers need spatial confidence. Scroll room context beats isolated white-background shots.",
        "result_headline": "Sit In Sculpted Comfort",
        "result_notes": "Interior scroll site with swatches, joinery gallery, room ideas, and delivery configurator.",
    },
    {
        "slug": "14_Premium_Wellness_Studio",
        "title": "Premium Wellness Studio",
        "product_label": "Forma Pilates Studio",
        "cover_hook": "Wellness studios sell transformation. Your site should breathe before the booking button.",
        "website_prompt": _site(
            "Build a premium pilates studio landing page for Forma. Nav: Classes, Instructors, Schedule, Membership. Hero 'Move With Intention' with first-class offer chip.",
            "Sections: class type cards (Reformer, Mat, Private), instructor bios, timetable embed, membership tiers, studio tour photo strip, FAQ on beginners.",
            "Soft stone, warm white, sage accent. Scroll hero uses studio light and reformer detail frames.",
        ),
        "image_prompt": _img(
            "Premium pilates studio hero for scroll frames. No text, 16:9. Reformer machine in sunlit studio, linen curtains, plants soft blur, polished wood floor reflection.",
            "Clean wellness aesthetic, natural light, calm energy. Human absence intentional - focus on space quality.",
            "Wide angle 28mm, soft shadows, neutral warm grade. Avoid gym bro energy, avoid neon accents.",
        ),
        "first_frame_prompt": "Wide studio interior multiple reformers, morning light, airy space, no text.",
        "last_frame_prompt": "Close reformer straps and carriage detail, tighter crop, no text.",
        "video_prompt": "Slow glide through studio aisle between reformers. Curtain light shifts subtly, calm wellness pacing, seamless loop.",
        "why_website": "Studios compete on vibe and schedule clarity. Cinematic scroll sells the room before the trial class.",
        "result_headline": "Move With Intention",
        "result_notes": "Wellness scroll site with class cards, instructor bios, schedule embed, and membership tiers.",
    },
    {
        "slug": "15_Luxury_Chocolate",
        "title": "Luxury Chocolate",
        "product_label": "Cacao Meridian Bonbons",
        "cover_hook": "Luxury chocolate is ceremony. Prompt a site you can almost taste.",
        "website_prompt": _site(
            "Create a luxury bonbon brand page for Cacao Meridian. Nav: Collections, Origins, Gifting, Shop. Hero 'Tempered To Perfection' with single-origin Venezuela 72% hero box.",
            "Sections: flavor collection grid with tasting notes, gifting configurator, tempering process timeline, corporate gifting form, shipping cold-pack explainer.",
            "Deep cocoa brown, champagne gold foil accents, cream backgrounds. Scroll hero uses bonbon macro sequence.",
        ),
        "image_prompt": _img(
            "Luxury chocolate hero for scroll frames. No text, 16:9. Assorted bonbons in open matte black box on marble, gold foil wrappers glinting, cocoa dust subtle.",
            "Macro ganache shine on cut bonbon, shallow DOF, patisserie campaign lighting. Warm highlights, dark elegant backdrop.",
            "Camera overhead 45 degrees. Rich browns without muddy shadows. Avoid cartoon candy colors.",
        ),
        "first_frame_prompt": "Wide box open on marble, full assortment visible, soft top light, no text.",
        "last_frame_prompt": "Macro single bonbon cut revealing ganache layers, tight crop, no text.",
        "video_prompt": "Slow push-in over open box toward single bonbon macro. Subtle foil glint, indulgent pacing, seamless loop.",
        "why_website": "Gift buyers need emotional pull and flavor clarity. Scroll macro motion sells craftsmanship before checkout.",
        "result_headline": "Tempered To Perfection",
        "result_notes": "Gifting scroll site with flavor grid, process timeline, configurator, and cold-ship explainer.",
    },
]

SLIDE_TEMPLATES = [
    "cover",
    "website_prompt",
    "image_prompt",
    "keyframes",
    "video_prompt",
    "why_website",
    "result_website",
    "cta",
]
